### ISSUE TITLE
km_find_report -> drop some variants

### ISSUE THREAD

**Issue by BoudSTER** [iric-soft/km#18]
Hi,

first of all thank you for this nice algorithm.
I have now passed several patients and the results are more than conclusive, thank you (alignment Free <3) . 
I have nevertheless for a patient a problem: when I use km_find_report one of the variants of interest confirm in SANGER disappears (whereas it is well present in the raw output of km).

**> I have linked the raw output of km :** 
[question_km.csv](https://github.com/iric-soft/km/files/9104171/question_km.csv)
The variant which is deleted is 678:t/C:679

**> The transformation into vcf gives :**
"""
##fileformat=VCFv4.1
##INFO=<ID=TYPE,Number=A,Type=String,Description="The type of variant, either Insertion, ITD, I&I, Deletion, Substitution or Indel.">
##INFO=<ID=TARGET,Number=A,Type=String,Description="Name of the sequencing that contains the mutation.">
##INFO=<ID=RATIO,Number=A,Type=String,Description="Ratio of mutation to reference.">
##INFO=<ID=MINCOV,Number=A,Type=String,Description="Minimum k-mer coverage of alternative allele.">
##INFO=<ID=REMOVED,Number=A,Type=String,Description="Number of removed bases.">
##INFO=<ID=ADDED,Number=A,Type=String,Description="Number of added bases.">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
chr9	133755457	.	TGGCAGTGGAATCCCTCTGACCGGCCCTCCTT	AGGCAGTGGAATCCCTCTGACCGGCCCTCCTC	.	.	TYPE=Substitution;TARGET=ABL1_exons_2-11_cut;RATIO=0.494;MINCOV=15;REMOVED=32;ADDED=32
chr9	133755488	.	T	C	.	.	TYPE=Substitution;TARGET=ABL1_exons_2-11_cut;RATIO=0.965;MINCOV=34;REMOVED=1;ADDED=1
"""

**> SANGER results NM_005157.4 ABL1 (for your information)**
c.757T>C: p.Y253H
and 
c.1457T>C:p.Phe486Ser

Do you have an explanation ? Thanks a lot for your help! :)

**Comment by feghalya** [comment]
Hello,

Happy to know you are enjoying using km! To answer your question, the variant you mention is excluded from the report because it has a minimum coverage of 0 (column Min_coverage). This happens when at least one kmer in your sequence has a count of 0 in the jellyfish database. By default, find_report excludes variants with Min_coverage equal to 0, but it can be changed in the arguments by specifying 'km find_report -m 0 ...'.

 Also, you might notice that the variant you mention is present on 2 different lines in km's raw output you attached. The first line contains the complete sequence, whereas the second line cuts the sequence around the mutation, which in your case gets rid of the null value in Min_coverage.

Hope this helps.

**Comment by BoudSTER** [comment]
Hi,

Thanks for your answer ! :)

Have a nice day 

BoudSTER.
