### ISSUE TITLE
km does not report complex indels found by VarDict

### ISSUE THREAD

**Issue by annaquaglieri16** [iric-soft/km#5]
Hi there, 

`km` doesn't report INDELs on KIT exon 8 compared to `VarDict` who finds a few complex indels. 

I am comparing INDELs called on AML RNA-Seq with `VarDict` and `km` on specific target regions. I run `VarDict` on the whole KIT gene region using the `.bed` file:

`chr4    54657428        54741215        KIT     +`

I then run `km` on separate KIT exons. Below is the target sequence used for exon 8 using hg38 fasta reference.

`>chr4:54723568-54723713
TCTGTTTTCCTGTAGCAAAACCAGAAATCCTGACTTACGACAGGCTCGTGAATGGCATGCTCCAATGTGTGGCAGCAGGATTCCCAGAGCCCACAATAGATTGGTATTTTTGTCCAGGAACTGAGCAGAGGTGAGATGATTATTT`

Here is an example of two INDELs that I get with `VarDict` but with `km`. They looks like something `km` should find. I validate them by looking into IGV:

```
                SampleName   variant_type                                 mutation_key                 mutation_det      pos
Sample1 indels-vardict                 chr4-54723603-TTACGACA-CCGGT KIT protein_altering_variant 54723603
Sample2 indels-vardict                      chr4-54723606-C-CTTCTTC        KIT inframe_insertion 54723606
```

I checked that reads supporting the INDEL are actually in the FASTQ files given to `km` and they are there. This is becase sometimes if the FASTQ files is not sorted by read name properly they might be discarded. 

 Am I doing something wrong with defining the target region?

Thanks!

Anna

**Comment by ericloud** [comment]
Hi Anna, 

I suspect that `km find_mutation` detect the INDEL but `km find_report` remove it, because some kmers count are equal to 0. Certainly, because your target sequence overlap a small part of intron on each side of the exon.
To verify this, you can run `km find_report` with `-m 0`.

If you want to keep the default value of `-m` (to filter potential false-positive), you need modify your target sequence by adding the previous exon, or at least a part of the end of this exon in function of the kmer's length you used. Indeed, the mutation is too close of the beginning of the exon (19bp) and you need at least 22bp of previous exon (if you use a kmer length of 31bp).

Below, you can find the two target sequences, which should work:
>chr4:54709424-54709539
ATACGTAAGTGAACTTCATCTAACGAGATTAAAAGGCACCGAAGGAGGCA
CTTACACATTCCTAGTGTCCAATTCTGACGTCAATGCTGCCATAGCATTT
AATGTTTATGTGAATA
>chr4:54723584-54723698
CAAAACCAGAAATCCTGACTTACGACAGGCTCGTGAATGGCATGCTCCAA
TGTGTGGCAGCAGGATTCCCAGAGCCCACAATAGATTGGTATTTTTGTCC
AGGAACTGAGCAGAG

>chr4:54709518-54709539
GCATTTAATGTTTATGTGAATA
>chr4:54723584-54723698
CAAAACCAGAAATCCTGACTTACGACAGGCTCGTGAATGGCATGCTCCAA
TGTGTGGCAGCAGGATTCCCAGAGCCCACAATAGATTGGTATTTTTGTCC
AGGAACTGAGCAGAG

If these target sequences doesn't work, then you need to check if all mutated kmers are present in your jellyfish datable. If I understand correctly the output of VarDict, you need replace TTACGACA by CCGGT and check all kmers with CCGGT into it, using `jellyfish query` cmd, like:
 - `jellyfish query [your_file].jf AATCCTGACCCGGTGGCTCGTGAATGGCATG`

If at least one kmer have a count of 0, you need to check which jellyfish's parameters filters these kmers from your reads (like the base quality parameters ('-Q+')) and fix it.

I do my best to be clear, but I'm not sure this the case :).
Also, we work on a new version of documentation to add a part "how to build your target sequence ?", your feedback could be really useful for us.

Eric.

**Comment by annaquaglieri16** [comment]
Thanks Eric!
Really appreaciate it. I will try to run it with -m 0 first.  

Also, you mentioned the need to increase the length of the target sequence. Does it matter how long is the target sequence? Maybe with longer targets km will be slower, but in cases where I cannot be 100% sure where exactly the INDEL will be, wouldn't it be better to give it the whole gene as a target regions for example?

Thanks!

Anna

**Comment by ericloud** [comment]
Hi Anna, 

km is design to made targeted analysis, which mean that more specific is your _question_, more the answer of km will be quick and accurate.
In the case your _question_ isn't really specific, km will run perfectly fine but it could take more time to answer and the the answer could be less accurate.

There are different way to create a _specific question_,: 
 - define a small target sequence is the most simple;
 - you can also reduce km ability to explore and find any variants. For example, if you are only interested to find INDEL with  _y_ bp inserted, you can reduce the number of km steps (`km find_mutation -s` ) to: `k_len - 1 + y` (_k_len_ the length of your kmer). See also `km find_mutation -b`.

Furthermore, km's abilities to give you an accurate output will depend of the complexity of the _subject of your question_ : 
 - The probability to have false positive variant increase if your target sequence have a lot of repeat regions, larger than your kmer length; 
 - Also, if your sample have a lot of homozygous variants into the target sequence (have we mention at the end of  the [third paragraph of _Sensitivity and precision_ ](https://www.biorxiv.org/content/10.1101/295808v2). In that case you could use `km find_report -i cluster` to report local variant of the target sequence.

Finally, you need to try by your self, if you can _design a question_ (target sequence + km's parameters) which allow a km's answer that satisfy your requirements in therm of execution times and accuracy. For us when km continue to run after 1 or 2 min, we interrupt km and try to change parameters or the target sequence.

I hope this answer is enough clear to be helpful.
Eric.

**Comment by annaquaglieri16** [comment]
Yes, it does!
Thank you for the explanation. 
Anna

**Comment by ericloud** [comment]
Hi Anna, 

a new version of km's documentation is available.
You will find a new section: [Design your traget sequence](https://github.com/iric-soft/km/blob/master/README.rst#design-your-target-sequence)

I hope this will be clear and helpful. 
and let us know if you have some feedback to improve it.

Regards,
Eric.

**Comment by annaquaglieri16** [comment]
Thanks @ericloud ! I will let you know when I look into it. 

Anna

**Comment by ericloud** [comment]
New update: 
A web portal is now available to assist you in the creation of your target sequences.
km-target: https://bioinfo.iric.ca/km-target/

I will close this issue, but fell free to add some update or open a new issue if need it.

Regards,
Eric.
