### ISSUE TITLE
Output in standard VCF format

### ISSUE THREAD

**Issue by annaquaglieri16** [iric-soft/km#6]
Hi there, 
I was wondering if there is any thought about adding the VCF as the standard or at least available output so to streamline the process with other sofwtare.

Thanks!

Anna

**Comment by ericloud** [comment]
Hi Anna,

@feghalya works on several subjects for the version 2 of km (branch fusion_finder) and a vcf output is one of them. Unfortunately this version 2 is far from being ready and it is not documented yet.

If you want try this version, You should be able to use km as usual IF :
 - the target sequence doesn't overlap a splicing.
 - you specify the strand and a name in the header, like below:
>chr2:25234341-25234405 | name=DNMT3A | strand=-

Otherwise we are thinking of adding the possibility of a vcf output for the current version, but it will be difficult before the end of this summer. 

Eric.

**Comment by annaquaglieri16** [comment]
Thanks @ericloud. Sounds good for now, I just wanted to check whether this option might be available at some point!

Anna

**Comment by ericloud** [comment]
Hi Anna, 

It's done by @feghalya. 

Eric.
